# Banco de Preguntas - DGSC Manual de Orientación para Puestos de Dirección Pública
# Referencias de página corregidas según el índice real del manual

BANCO_COMPLETO = [

# BANCO DE PREGUNTAS - TEMA 1
# Generalidades del Estado de Derecho Costarricense
# Fuente: Manual de Orientación para el Ingreso y Ejercicio de Puestos de Dirección Pública (2019)
# Páginas 5-18 del manual

    # ── 1.1 ELEMENTOS DEL ESTADO ──────────────────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     '¿Cómo define Romero (2002) al Estado en el manual?',
     'Persona jurídica de mayor relevancia en el ordenamiento legal de una sociedad y en un territorio dado',
     'Organización política que ejerce el mando exclusivo sobre los ciudadanos',
     'Conjunto de instituciones privadas que regulan la convivencia social',
     'Entidad supranacional encargada de dictar normas de carácter internacional',
     'Manual p.7 - Sección 1.1: Romero (2002, p.12) define al Estado como "Persona jurídica de mayor relevancia en el ordenamiento legal de una sociedad y en un territorio dado".',
     'basico', 'p.7'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los tres elementos del Estado que presenta el manual?',
     'Población, Territorio y Soberanía',
     'Poder, Territorio y Ciudadanía',
     'Ley, Gobierno y Sociedad',
     'Nación, Constitución y Administración',
     'Manual p.7 - Sección 1.1: El manual identifica tres elementos del Estado: Población, Territorio y Soberanía.',
     'basico', 'p.7'),

    # ── 1.2 PRINCIPIOS DEL ESTADO DE DERECHO ─────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     'Según la Sección 1.2, ¿cuál de los siguientes es un principio del Estado de Derecho?',
     'Sujeción del Estado al bloque de legalidad',
     'Supremacía de la voluntad del gobernante sobre la ley',
     'Concentración de los poderes públicos en el Ejecutivo',
     'Exclusión de los ciudadanos del control político',
     'Manual p.8 - Sección 1.2: Uno de los principios del Estado de Derecho es la sujeción del Estado al bloque de legalidad.',
     'basico', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué principio del Estado de Derecho establece que ciertas materias son monopolio del Poder Legislativo?',
     'Reserva de ley',
     'Jerarquía normativa',
     'Descentralización funcional',
     'Potestad reglamentaria',
     'Manual p.8 - Sección 1.2: El principio de "Reserva de ley" señala que ciertas materias son monopolio del Poder Legislativo.',
     'intermedio', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué establece el principio de subordinación de la Administración Pública a los Tribunales?',
     'Que la Administración Pública está sujeta al control de los Tribunales de Justicia',
     'Que los Tribunales deben obedecer las disposiciones de la Administración',
     'Que el Poder Judicial depende presupuestariamente del Ejecutivo',
     'Que los jueces son nombrados por la Administración Pública',
     'Manual p.8 - Sección 1.2: La subordinación de la Administración Pública a los Tribunales es uno de los principios del Estado de Derecho.',
     'intermedio', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     'La separación de poderes públicos es uno de los principios del Estado de Derecho. ¿Qué implica para los Poderes del Estado según el manual?',
     'Que gozan de independencia total en el ejercicio de sus atribuciones y no están subordinados a ningún otro órgano estatal',
     'Que cada Poder puede ejercer funciones de los demás cuando lo considere conveniente',
     'Que el Poder Ejecutivo coordina y supervisa los actos de los otros Poderes',
     'Que la Asamblea Legislativa tiene supremacía sobre los demás Poderes',
     'Manual p.9 - Sección 1.2 y 1.5: Los Poderes gozan de independencia total; sus relaciones son de colaboración y respeto recíproco (Hernández, 2005, p.27).',
     'intermedio', 'p.9'),

    # ── 1.3 FUENTES DEL DERECHO Y SU JERARQUIZACIÓN ─────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     '¿Cómo clasifica el manual las fuentes del Derecho?',
     'En fuentes escritas y fuentes no escritas',
     'En fuentes nacionales e internacionales',
     'En fuentes primarias y fuentes secundarias',
     'En fuentes constitucionales y fuentes legales',
     'Manual p.8 - Sección 1.3: Las fuentes del Derecho se clasifican en escritas (Constitución, Tratados, Leyes, Reglamentos, Decretos, Circulares) y no escritas (Principios Generales, Costumbre, Jurisprudencia).',
     'basico', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son las fuentes no escritas del Derecho que menciona el manual?',
     'Principios Generales del Derecho, Costumbre y Jurisprudencia',
     'Decretos, Circulares y Directrices',
     'Reglamentos, Directrices y Tratados',
     'Doctrina, Opiniones consultivas y Convenios',
     'Manual p.8 - Sección 1.3: Las fuentes no escritas son los Principios Generales del Derecho, la Costumbre y la Jurisprudencia.',
     'intermedio', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     'En la jerarquización de las fuentes escritas del Derecho, ¿qué ocupa el primer lugar?',
     'La Constitución Política',
     'Los Tratados y Convenios Internacionales',
     'Las Leyes y actos con valor de ley',
     'Los Reglamentos del Poder Ejecutivo',
     'Manual p.8 - Sección 1.3: La Constitución Política ocupa el primer lugar en la jerarquización de fuentes escritas.',
     'basico', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     'Según la jerarquización de fuentes del manual, ¿qué posición ocupan los Tratados y Convenios Internacionales?',
     'Segundo lugar, después de la Constitución Política',
     'Primer lugar, por encima de la Constitución',
     'Tercer lugar, junto con las Leyes',
     'Cuarto lugar, junto con los Reglamentos',
     'Manual p.8 - Sección 1.3: Los Tratados y convenios internacionales ocupan el segundo lugar en la jerarquía de fuentes escritas.',
     'intermedio', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     'En el orden jerárquico de las fuentes escritas, ¿qué nivel ocupan las Leyes y actos con valor de ley?',
     'Tercer lugar',
     'Segundo lugar',
     'Cuarto lugar',
     'Quinto lugar',
     'Manual p.8 - Sección 1.3: Las Leyes y actos con valor de ley ocupan el tercer lugar en la jerarquía de fuentes escritas.',
     'intermedio', 'p.8'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué fuentes escritas del Derecho menciona el manual en los niveles inferiores de la jerarquía, después de las Leyes?',
     'Reglamentos, Decretos y Circulares',
     'Tratados, Convenios y Pactos',
     'Sentencias, Votos y Resoluciones',
     'Directrices, Instructivos y Manuales',
     'Manual p.8 - Sección 1.3: En los niveles inferiores se encuentran los Reglamentos, Decretos y Circulares.',
     'intermedio', 'p.8'),

    # ── 1.4 RÉGIMEN DE DERECHOS FUNDAMENTALES ────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     'Según Hernández (2005), citado en el manual, ¿cuándo se transforman las libertades en públicas?',
     'Cuando entran a formar parte del Derecho positivo',
     'Cuando son reconocidas por los medios de comunicación',
     'Cuando el ciudadano cumple la mayoría de edad',
     'Cuando son aprobadas por decreto ejecutivo',
     'Manual p.9 - Sección 1.4: Hernández (2005, p.170) indica que "Todas las libertades se transforman en públicas justamente cuando entran a formar parte del Derecho positivo".',
     'avanzado', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cómo define el manual los Derechos Individuales?',
     'Aquellas libertades públicas que corresponden a la persona en cuanto ser individual e intransferible',
     'Los derechos que tiene la persona como miembro de un grupo social determinado',
     'Los derechos que ejercen los ciudadanos en relación con la estructura política del Estado',
     'Los derechos económicos que el Estado garantiza a todos los habitantes del territorio',
     'Manual p.9 - Sección 1.4: Los derechos individuales corresponden a la persona en cuanto ser individual e intransferible (Título IV Constitución Política).',
     'basico', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿En qué Título de la Constitución Política se encuentran los Derechos Individuales según el manual?',
     'Título IV',
     'Título V',
     'Título VIII',
     'Título IX',
     'Manual p.9 - Sección 1.4: Los derechos individuales se encuentran en el Título IV de la Constitución Política.',
     'intermedio', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cómo define el manual los Derechos Sociales?',
     'Derechos que tiene la persona en cuanto forma parte de un grupo social determinado, para asegurar el disfrute de los intereses de su pertenencia a esos grupos',
     'Derechos que corresponden a la persona en cuanto ser individual e intransferible',
     'Derechos que ejercen los ciudadanos en relación con la estructura político-jurídica del Estado',
     'Derechos exclusivos de los funcionarios públicos en ejercicio de sus cargos',
     'Manual p.9 - Sección 1.4: Los derechos sociales son los que tiene la persona en cuanto forma parte de un grupo social, para asegurar los intereses derivados de esa pertenencia (Título V Constitución Política).',
     'basico', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿En qué Título de la Constitución Política se ubican los Derechos Sociales?',
     'Título V',
     'Título IV',
     'Título VIII',
     'Título X',
     'Manual p.9 - Sección 1.4: Los derechos sociales se encuentran en el Título V de la Constitución Política.',
     'intermedio', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cómo define el manual los Derechos Políticos?',
     'Aquellos que ejercen los ciudadanos en relación con la estructura político-jurídica del Estado',
     'Los derechos que garantizan la libertad individual de la persona',
     'Los derechos económicos y laborales del trabajador público',
     'Las garantías que protegen a los grupos sociales vulnerables',
     'Manual p.9 - Sección 1.4: Los derechos políticos son los que ejercen los ciudadanos en relación con la estructura político-jurídica del Estado (Título VIII, Caps. I y II Constitución Política).',
     'basico', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿En qué Título y Capítulos de la Constitución se encuentran los Derechos Políticos según el manual?',
     'Título VIII, Capítulos I y II',
     'Título IV, Capítulo III',
     'Título V, Capítulo I',
     'Título IX, Capítulo IV',
     'Manual p.9 - Sección 1.4: Los derechos políticos se encuentran en el Título VIII, Capítulos I y II de la Constitución Política.',
     'intermedio', 'p.9'),

    # ── 1.5 DIVISIÓN DE PODERES ───────────────────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     'Según el Artículo 9° de la Constitución Política citado en el manual, ¿cómo es el Gobierno de la República?',
     'Popular, representativo, participativo, alternativo y responsable',
     'Democrático, federal, independiente y pluriétnico',
     'Central, absoluto, hereditario y permanente',
     'Técnico, administrativo, meritocrático y civil',
     'Manual p.9 - Sección 1.5: El Art. 9 establece que el Gobierno es "popular, representativo, participativo, alternativo y responsable".',
     'basico', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     'Según el Artículo 9° constitucional, ¿cuáles son los tres Poderes del Estado que ejercen el gobierno?',
     'El Legislativo, el Ejecutivo y el Judicial',
     'El Ejecutivo, el Judicial y el Electoral',
     'El Legislativo, el Ejecutivo y el Electoral',
     'El Ejecutivo, el Contralor y el Judicial',
     'Manual p.9 - Sección 1.5: El Art. 9 establece que el gobierno lo ejercen el pueblo y tres Poderes: el Legislativo, el Ejecutivo y el Judicial.',
     'basico', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué establece el Artículo 9° constitucional sobre la delegación de funciones entre los Poderes?',
     'Ninguno de los Poderes puede delegar el ejercicio de funciones que le son propias',
     'El Ejecutivo puede delegar en el Legislativo con acuerdo de Consejo de Gobierno',
     'La delegación es posible si la Sala Constitucional lo autoriza',
     'Se permite la delegación en situaciones de emergencia nacional declarada',
     'Manual p.9 - Sección 1.5: El Art. 9 establece expresamente que "Ninguno de los Poderes puede delegar el ejercicio de funciones que le son propias".',
     'intermedio', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     'Según el Artículo 9° constitucional citado en el manual, ¿qué rango e independencia tiene el Tribunal Supremo de Elecciones (TSE)?',
     'El mismo rango e independencia de los Poderes del Estado',
     'Es un órgano subordinado al Poder Judicial',
     'Tiene rango ministerial, dependiente del Ejecutivo',
     'Es un órgano auxiliar de la Asamblea Legislativa',
     'Manual p.9 - Sección 1.5: El Art. 9 establece que el TSE tiene "el rango e independencia de los Poderes del Estado".',
     'intermedio', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué función le atribuye la Constitución al TSE respecto al sufragio?',
     'La organización, dirección y vigilancia de los actos relativos al sufragio, de forma exclusiva e independiente',
     'La fiscalización del financiamiento de los partidos políticos en forma compartida con la CGR',
     'La interpretación de la Constitución en materia electoral junto con la Sala IV',
     'El escrutinio de los votos, función que comparte con las Juntas Electorales',
     'Manual p.9 - Sección 1.5: El Art. 9 le atribuye al TSE "en forma exclusiva e independiente la organización, dirección y vigilancia de los actos relativos al sufragio".',
     'basico', 'p.9'),

    ('1', 'Generalidades del Estado de Derecho',
     'Según el manual, ¿cuál es la característica fundamental de los Poderes estatales respecto a sus atribuciones?',
     'Gozan de independencia total en el ejercicio de sus atribuciones y no están jurídicamente subordinados a ningún otro órgano estatal',
     'Están subordinados jerárquicamente al Poder Ejecutivo en materia presupuestaria',
     'Deben consultar mutuamente sus decisiones antes de ejecutarlas',
     'La Asamblea Legislativa tiene supremacía sobre los demás Poderes en materia de control',
     'Manual p.9 - Sección 1.5: Citando a Hernández (2005, p.27), los Poderes "gozan de independencia total en el ejercicio de sus atribuciones, por lo que no están jurídicamente subordinados a ningún otro órgano estatal".',
     'intermedio', 'p.9'),

    # ── 1.5.1 PODER LEGISLATIVO ───────────────────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     '¿En qué Título de la Constitución Política está normado el Poder Legislativo?',
     'Título IX',
     'Título VIII',
     'Título X',
     'Título XI',
     'Manual p.10 - Sección 1.5.1: El Poder Legislativo está normado en el Título IX de la Constitución Política.',
     'intermedio', 'p.10'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuántos diputados integran la Asamblea Legislativa?',
     '57 diputados',
     '45 diputados',
     '63 diputados',
     '50 diputados',
     'Manual p.10 - Sección 1.5.1: La Asamblea Legislativa está integrada por 57 diputados.',
     'basico', 'p.10'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cómo se determina el número de diputados por provincia según el manual?',
     'Es proporcional a la población de cada provincia y lo determina el Tribunal Supremo de Elecciones',
     'Es igual para todas las provincias y lo establece la Asamblea Legislativa',
     'Lo determina el Poder Ejecutivo mediante decreto según el último censo',
     'Es fijo por disposición constitucional en ocho diputados por provincia',
     'Manual p.10 - Sección 1.5.1: El número de diputados por provincia es proporcional a su población y lo determina el Tribunal Supremo de Elecciones.',
     'intermedio', 'p.10'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cada cuánto tiempo se eligen los diputados y qué tipo de cargos son?',
     'Cada 4 años, son cargos de elección popular',
     'Cada 8 años, son nombrados por la Corte Suprema de Justicia',
     'Cada 6 años, son designados por el Presidente de la República',
     'Cada 5 años, son nombrados por el Consejo de Gobierno',
     'Manual p.10 - Sección 1.5.1: Los diputados son cargos de elección popular cada 4 años.',
     'basico', 'p.10'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los requisitos para ser Diputado según el Artículo 108 de la Constitución Política?',
     'Ser ciudadano en ejercicio, ser costarricense por nacimiento o naturalizado con diez años de residencia, y haber cumplido veintiún años',
     'Ser costarricense por nacimiento, mayor de 30 años y tener título universitario',
     'Ser ciudadano en ejercicio, mayor de 25 años y no tener antecedentes penales',
     'Ser costarricense por nacimiento, del estado seglar y mayor de 21 años',
     'Manual p.10 - Sección 1.5.1: Los requisitos del art. 108 son: ser ciudadano en ejercicio, ser costarricense por nacimiento o naturalizado con 10 años de residencia, y haber cumplido 21 años.',
     'intermedio', 'p.10'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son las cuatro formas de organización de la Asamblea Legislativa que menciona el manual?',
     'Plenario, Comisión Permanente Ordinaria, Comisión Permanente Especial y Comisión Plena',
     'Directorio, Plenario, Secretaría y Comisiones Especiales',
     'Plenario, Subcomisiones, Comités Técnicos y Grupos de Trabajo',
     'Cámara Alta, Cámara Baja, Comisiones Mixtas y Pleno',
     'Manual p.10 - Sección 1.5.1: La organización incluye: Plenario, Comisión Permanente Ordinaria, Comisión Permanente Especial y Comisión Plena.',
     'avanzado', 'p.10'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son las cinco Comisiones Permanentes Ordinarias de la Asamblea Legislativa que menciona el manual?',
     'Asuntos Agropecuarios, Asuntos Económicos, Asuntos Jurídicos, Asuntos Sociales y Gobierno y Administración',
     'Hacienda, Educación, Salud, Seguridad y Ambiente',
     'Legislación, Control, Nombramiento, Relaciones Exteriores y Presupuesto',
     'Infraestructura, Tecnología, Derechos Humanos, Ciencia y Turismo',
     'Manual p.10 - Sección 1.5.1: Las cinco Comisiones Permanentes Ordinarias son: Asuntos Agropecuarios, Económicos, Jurídicos, Sociales y Gobierno y Administración (todas desde el 01/05/1948).',
     'avanzado', 'p.10'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son las cuatro atribuciones principales del Poder Legislativo que clasifica el manual?',
     'Función Legislativa, Control Político, Función Jurisdiccional y Dirección Política',
     'Legislar, Juzgar, Ejecutar y Fiscalizar',
     'Crear leyes, Aplicar sanciones, Recaudar impuestos y Elegir magistrados',
     'Deliberar, Aprobar, Vetar y Publicar',
     'Manual p.11 - Sección 1.5.1: Las atribuciones son: Función Legislativa, Control Político, Función Jurisdiccional y Dirección Política.',
     'intermedio', 'p.11'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué incluye la función de Control Político de la Asamblea Legislativa?',
     'Interpelaciones de los Ministros, votos de censura a Ministros y comisiones de investigación',
     'Dictar leyes, reformarlas, derogarlas e interpretarlas',
     'Nombrar a los altos funcionarios y aprobar tratados internacionales',
     'Ejercer el derecho de gracia y levantar el fuero de improcedibilidad penal',
     'Manual p.11 - Sección 1.5.1: El Control Político incluye interpelaciones a Ministros, votos de censura y comisiones de investigación.',
     'intermedio', 'p.11'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuál es el quórum requerido para que la Asamblea Legislativa pueda sesionar?',
     '38 diputados',
     '30 diputados',
     '45 diputados',
     '29 diputados',
     'Manual p.11 - Sección 1.5.1: El quórum para sesionar es de 38 diputados.',
     'intermedio', 'p.11'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los períodos de sesiones ordinarias de la Asamblea Legislativa según el manual?',
     'Del 1° de mayo al 31 de julio y del 1° de setiembre al 30 de noviembre',
     'Del 1° de enero al 30 de junio y del 1° de agosto al 31 de diciembre',
     'Del 15 de enero al 15 de julio y del 15 de agosto al 15 de diciembre',
     'Todo el año, sin distinción entre ordinarias y extraordinarias',
     'Manual p.11 - Sección 1.5.1: Las sesiones ordinarias son del 01 de mayo al 31 de julio y del 01 de setiembre al 30 de noviembre.',
     'intermedio', 'p.11'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Quién convoca las sesiones extraordinarias de la Asamblea Legislativa?',
     'El Poder Ejecutivo, con asuntos específicos',
     'El Presidente de la Asamblea Legislativa',
     'La Sala Constitucional ante una urgencia nacional',
     'Cualquier fracción legislativa con más de 10 diputados',
     'Manual p.11 - Sección 1.5.1: Las sesiones extraordinarias son convocadas por el Poder Ejecutivo, con asuntos específicos.',
     'basico', 'p.11'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son las cuatro fases del Proceso de Formación de la Ley que describe el manual?',
     'Fase Introductoria, Fase Deliberativa, Fase de Aprobación y Fase de Eficacia',
     'Iniciativa, Debate, Votación y Publicación',
     'Propuesta, Comisión, Plenario y Promulgación',
     'Anteproyecto, Proyecto, Dictamen y Decreto',
     'Manual p.12 - Sección 1.5.1: Las fases del proceso de formación de la ley son: Introductoria, Deliberativa, de Aprobación y de Eficacia.',
     'avanzado', 'p.12'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los órganos auxiliares del Poder Legislativo que menciona el manual?',
     'La Contraloría General de la República y la Defensoría de los Habitantes',
     'La Procuraduría General y el Banco Central',
     'El Tribunal Supremo de Elecciones y el Poder Judicial',
     'La Sala Constitucional y el MIDEPLAN',
     'Manual p.12 - Sección 1.5.1: Los órganos auxiliares del Poder Legislativo son la Contraloría General de la República y la Defensoría de los Habitantes.',
     'basico', 'p.12'),

    ('1', 'Generalidades del Estado de Derecho',
     'Según el manual, ¿qué normativa rige a la Contraloría General de la República?',
     'Los artículos 183 y 184 de la Constitución Política y la Ley Orgánica N° 7428',
     'El artículo 9 constitucional y la Ley General de la Administración Pública',
     'Los artículos 99 a 104 de la Constitución y la Ley del TSE',
     'El artículo 169 constitucional y la Ley de Municipalidades',
     'Manual p.13 - Sección 1.5.1: La CGR está normada por los arts. 183 y 184 de la Constitución Política y la Ley Orgánica N° 7428.',
     'intermedio', 'p.13'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Por cuánto tiempo son nombrados el Contralor y el Subcontralor, y quién los nombra?',
     'Por un período de 8 años, nombrados por la Asamblea Legislativa',
     'Por 4 años, nombrados por el Presidente de la República',
     'Por 6 años, elegidos por la Corte Suprema de Justicia',
     'Por 5 años, designados por el Consejo de Gobierno',
     'Manual p.13 - Sección 1.5.1: El Contralor y Subcontralor son nombrados por la Asamblea Legislativa por un período de 8 años.',
     'intermedio', 'p.13'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son las funciones de la Contraloría General de la República descritas en el manual?',
     'Aprobación de presupuestos, refrendo de contratos, estudios a instituciones públicas y sanciones',
     'Dictar leyes, interponer recursos de amparo y aprobar tratados internacionales',
     'Nombrar magistrados, controlar la deuda pública y regular los partidos políticos',
     'Organizar elecciones, expedir cédulas de identidad y resolver conflictos constitucionales',
     'Manual p.13 - Sección 1.5.1: Las funciones de la CGR son: aprobación de presupuestos, refrendo de contratos, estudios a instituciones y sanciones.',
     'basico', 'p.13'),

    ('1', 'Generalidades del Estado de Derecho',
     'Según el Artículo 1 de la Ley 7319, ¿cuál es la función de la Defensoría de los Habitantes?',
     'Proteger los derechos e intereses de los habitantes y velar porque el funcionamiento del sector público se ajuste a la moral, la justicia, la Constitución y las leyes',
     'Fiscalizar el uso de los recursos públicos y sancionar el enriquecimiento ilícito',
     'Interpretar la Constitución y resolver recursos de inconstitucionalidad',
     'Organizar las elecciones populares y vigilar la pureza del sufragio',
     'Manual p.13 - Sección 1.5.1: El art. 1 de la Ley 7319 define a la Defensoría como el órgano que protege derechos e intereses de los habitantes y vela por el ajuste del sector público a la moral, justicia, Constitución y leyes.',
     'basico', 'p.13'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuánto dura en el cargo el Defensor de los Habitantes y quién lo nombra?',
     '4 años, nombrado por la Asamblea Legislativa',
     '6 años, elegido por el pueblo mediante votación directa',
     '8 años, nombrado por el Consejo de Gobierno',
     '5 años, designado por la Sala Constitucional',
     'Manual p.13 - Sección 1.5.1: Las autoridades de la Defensoría (Defensor y Defensor Adjunto) son nombradas por la Asamblea Legislativa por 4 años.',
     'intermedio', 'p.13'),

    ('1', 'Generalidades del Estado de Derecho',
     'Según el manual, ¿con qué es incompatible el cargo de Defensor de los Habitantes?',
     'Con cualquier cargo público',
     'Con ejercer la profesión de abogado',
     'Con tener doble nacionalidad',
     'Con ser afiliado a un partido político',
     'Manual p.13 - Sección 1.5.1: El cargo de Defensor es incompatible con cualquier cargo público.',
     'intermedio', 'p.13'),

    # ── 1.5.2 PODER EJECUTIVO ─────────────────────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     '¿En qué Título de la Constitución Política está normado el Poder Ejecutivo y qué función ejerce?',
     'Título X; ejerce la función política y administrativa del Estado',
     'Título IX; ejerce la función legislativa del Estado',
     'Título XI; ejerce la función jurisdiccional del Estado',
     'Título VIII; ejerce la función electoral del Estado',
     'Manual p.14 - Sección 1.5.2: El Poder Ejecutivo está normado en el Título X y ejerce la función política y administrativa del Estado.',
     'intermedio', 'p.14'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los requisitos para ser Presidente o Vicepresidente de la República según el manual?',
     'Costarricense por nacimiento, ciudadano en ejercicio, del estado seglar y mayor de 30 años',
     'Costarricense por nacimiento o naturalización, mayor de 25 años y título universitario',
     'Ciudadano en ejercicio, mayor de 21 años y costarricense por nacimiento',
     'Costarricense por nacimiento, del estado seglar, mayor de 35 años y abogado',
     'Manual p.14 - Sección 1.5.2: Los requisitos son: costarricense por nacimiento, ciudadano en ejercicio, del estado seglar y mayor de 30 años.',
     'intermedio', 'p.14'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuándo toman posesión el Presidente y Vicepresidentes de la República y ante quién se juramentan?',
     'Toman posesión el 8 de mayo y se juramentan ante la Asamblea Legislativa',
     'Toman posesión el 1° de mayo y se juramentan ante la Corte Suprema de Justicia',
     'Toman posesión el 8 de mayo y se juramentan ante la Sala Constitucional',
     'Toman posesión el 15 de mayo y se juramentan ante el Tribunal Supremo de Elecciones',
     'Manual p.14 - Sección 1.5.2: El Presidente y Vicepresidentes toman posesión el 8 de mayo y se juramentan ante la Asamblea Legislativa.',
     'intermedio', 'p.14'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Con qué porcentaje de votos válidos emitidos se gana la elección presidencial en primera ronda?',
     'Con el 40% de los votos válidos emitidos',
     'Con el 50% más uno de los votos válidos emitidos',
     'Con el 45% de los votos válidos emitidos',
     'Con simple mayoría relativa, sin porcentaje mínimo',
     'Manual p.14 - Sección 1.5.2: La elección presidencial se gana con el 40% de los votos válidos emitidos.',
     'basico', 'p.14'),

    ('1', 'Generalidades del Estado de Derecho',
     'Si en la elección presidencial no se alcanza el porcentaje requerido en primera ronda, ¿cuándo se celebra la segunda ronda?',
     'El primer domingo de abril',
     'El primer domingo de junio',
     'El primer domingo de mayo',
     'El primer domingo de febrero del año siguiente',
     'Manual p.14 - Sección 1.5.2: Si no se alcanza el 40% de votos en primera ronda, se acude a segunda ronda el primer domingo de abril.',
     'intermedio', 'p.14'),

    ('1', 'Generalidades del Estado de Derecho',
     'Dentro de los deberes y atribuciones del Presidente de la República, ¿qué debe presentar a la Asamblea Legislativa el 1° de mayo?',
     'Un informe de rendición de cuentas sobre la gestión',
     'El proyecto de presupuesto ordinario para el siguiente año',
     'La propuesta del Plan Nacional de Desarrollo actualizado',
     'La lista de los nuevos nombramientos diplomáticos',
     'Manual p.14 - Sección 1.5.2: El Presidente debe presentar a la Asamblea Legislativa el 1° de mayo un informe de rendición de cuentas sobre la gestión.',
     'basico', 'p.14'),

    ('1', 'Generalidades del Estado de Derecho',
     'Las atribuciones del Poder Ejecutivo (Presidente más Ministro respectivo) se clasifican en varias naturalezas. ¿Cuáles menciona el manual?',
     'Naturaleza política, administrativas, dirección política, de carácter normativo, político-internacionales y financieras',
     'Legislativas, judiciales, electorales y administrativas',
     'Económicas, sociales, culturales y ambientales',
     'Nacionales, municipales, regionales e internacionales',
     'Manual p.14 - Sección 1.5.2: Las atribuciones del Ejecutivo (Presidente + Ministro) son: de naturaleza política, administrativas, dirección política, de carácter normativo, político-internacionales y financieras.',
     'avanzado', 'p.14'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los requisitos para ser Ministro de Estado según el manual?',
     'Ciudadano en ejercicio, costarricense por nacimiento o naturalizado con 10 años de residencia, del estado seglar y haber cumplido 25 años',
     'Costarricense por nacimiento, ciudadano en ejercicio, del estado seglar y mayor de 30 años',
     'Mayor de 35 años, abogado con 10 años de ejercicio, costarricense por nacimiento',
     'Ciudadano en ejercicio, mayor de 21 años y tener título universitario',
     'Manual p.15 - Sección 1.5.2: Los requisitos para ser Ministro son: ciudadano en ejercicio, costarricense por nacimiento o naturalizado con 10 años de residencia, del estado seglar y haber cumplido 25 años.',
     'intermedio', 'p.15'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué debe presentar el Ministro a la Asamblea Legislativa y en qué plazo?',
     'Una memoria de los asuntos de su Ministerio en los primeros 15 días del mes de mayo',
     'Un informe trimestral de ejecución presupuestaria durante todo el año',
     'El plan operativo institucional en los primeros 30 días de cada año',
     'Un informe anual de rendición de cuentas el 1° de enero de cada año',
     'Manual p.15 - Sección 1.5.2: El Ministro debe presentar a la Asamblea Legislativa una memoria de los asuntos de su Ministerio en los primeros 15 días del mes de mayo.',
     'intermedio', 'p.15'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué es el Consejo de Gobierno y quiénes lo integran?',
     'Está formado por el Presidente de la República y la totalidad de sus Ministros',
     'Lo integran el Presidente, los Vicepresidentes y los Presidentes de las instituciones autónomas',
     'Lo conforman el Presidente, los Ministros y los Magistrados de la Corte Suprema',
     'Está integrado por el Presidente, los Vicepresidentes y los jefes de fracción legislativa',
     'Manual p.15 - Sección 1.5.2: El Consejo de Gobierno está formado por el Presidente de la República y la totalidad de sus Ministros.',
     'basico', 'p.15'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son algunas de las funciones del Consejo de Gobierno que menciona el manual?',
     'Solicitar declaratoria de defensa nacional, ejercer el derecho de gracia, nombrar diplomáticos y directores de instituciones autónomas',
     'Dictar leyes, aprobar tratados y nombrar magistrados',
     'Interpretar la Constitución, resolver conflictos de poderes y declarar estados de excepción',
     'Organizar elecciones, fiscalizar partidos y validar resultados electorales',
     'Manual p.15 - Sección 1.5.2: El Consejo de Gobierno tiene funciones como: solicitar declaratoria de defensa, ejercer el derecho de gracia, nombrar diplomáticos y directores de instituciones autónomas.',
     'avanzado', 'p.15'),

    # ── 1.5.3 TRIBUNAL SUPREMO DE ELECCIONES ─────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     '¿En qué artículos de la Constitución Política está normado el TSE?',
     'Artículos 99 a 104 del Título VIII, Capítulo III',
     'Artículos 183 y 184 del Título IX',
     'Artículos 159 a 165 del Título XI',
     'Artículos 9 y 10 del Título I',
     'Manual p.15 - Sección 1.5.3: El TSE está normado en el Título VIII, Capítulo III, artículos 99-104 de la Constitución Política.',
     'intermedio', 'p.15'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuántos Magistrados Propietarios y Suplentes tiene el TSE según el manual?',
     '3 Magistrados Propietarios y 6 Magistrados Suplentes',
     '5 Magistrados Propietarios y 5 Magistrados Suplentes',
     '7 Magistrados Propietarios y 7 Magistrados Suplentes',
     '4 Magistrados Propietarios y 8 Magistrados Suplentes',
     'Manual p.15 - Sección 1.5.3: El TSE está integrado por 3 Magistrados Propietarios y 6 Magistrados Suplentes.',
     'intermedio', 'p.15'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Quién elige a los Magistrados del TSE y por cuánto tiempo duran en el cargo?',
     'Son elegidos por la Corte Suprema de Justicia por 6 años',
     'Son elegidos por la Asamblea Legislativa por 8 años',
     'Son nombrados por el Consejo de Gobierno por 4 años',
     'Son elegidos por el Plenario Legislativo por 6 años',
     'Manual p.15 - Sección 1.5.3: Los Magistrados del TSE son elegidos por la Corte Suprema de Justicia y duran 6 años.',
     'intermedio', 'p.15'),

    ('1', 'Generalidades del Estado de Derecho',
     'Entre las funciones del TSE, ¿cuál de las siguientes menciona el manual?',
     'Interpretar las disposiciones legales en materia electoral',
     'Aprobar las leyes de carácter electoral',
     'Nombrar a los Ministros de Gobernación y Policía',
     'Fiscalizar el presupuesto de los partidos políticos con la CGR',
     'Manual p.16 - Sección 1.5.3: Una de las funciones del TSE es interpretar las disposiciones legales en materia electoral.',
     'basico', 'p.16'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son las funciones del Registro Civil como órgano auxiliar del TSE?',
     'Formar las listas de electores, expedir cédulas de identidad y resolver solicitudes de ciudadanía',
     'Organizar elecciones, proclamar resultados y escrutar votos',
     'Investigar parcialidad política de servidores y vigilar la libertad electoral',
     'Convocar a referéndum, interpretar normas electorales y nombrar Juntas Electorales',
     'Manual p.16 - Sección 1.5.3: El Registro Civil (órgano auxiliar del TSE) tiene las funciones de formar las listas de electores, expedir cédulas de identidad y resolver solicitudes para adquirir y recuperar la ciudadanía.',
     'intermedio', 'p.16'),

    # ── 1.5.4 PODER JUDICIAL ──────────────────────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     '¿En qué Título de la Constitución está normado el Poder Judicial y cuál es su máximo órgano?',
     'Título XI; la Corte Suprema de Justicia',
     'Título IX; la Sala Constitucional',
     'Título X; el Tribunal de Casación',
     'Título VIII; el Tribunal Supremo de Justicia',
     'Manual p.16 - Sección 1.5.4: El Poder Judicial está normado en el Título XI y la Corte Suprema de Justicia es su máximo órgano.',
     'intermedio', 'p.16'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Quién elige a los Magistrados de la Corte Suprema de Justicia y por cuánto tiempo?',
     'La Asamblea Legislativa, por 8 años',
     'El Presidente de la República, por 6 años',
     'La Corte Suprema misma, por 8 años',
     'El Consejo de Gobierno, por 4 años',
     'Manual p.16 - Sección 1.5.4: Los Magistrados son elegidos por la Asamblea Legislativa por 8 años.',
     'basico', 'p.16'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los requisitos para ser Magistrado de la Corte Suprema de Justicia según el manual?',
     'Costarricense por nacimiento o naturalizado con 10 años de residencia, ciudadano en ejercicio, del estado seglar, mayor de 35 años y abogado con al menos 10 años de ejercicio profesional',
     'Ciudadano en ejercicio, mayor de 30 años, costarricense por nacimiento y título de posgrado',
     'Costarricense por nacimiento, del estado seglar, mayor de 25 años y juez por 5 años',
     'Mayor de 40 años, doctor en derecho, costarricense por nacimiento y sin antecedentes penales',
     'Manual p.16 - Sección 1.5.4: Los requisitos del art. 159 C.P. son: costarricense por nacimiento o naturalizado con 10 años de residencia, ciudadano en ejercicio, del estado seglar, mayor de 35 años y abogado con 10 años mínimo de ejercicio.',
     'avanzado', 'p.16'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuál es la función del Poder Judicial descrita en el manual?',
     'Conocer causas civiles, penales, comerciales, de trabajo y contencioso-administrativas, resolver sobre ellas y ejecutar las resoluciones',
     'Dictar leyes, aprobarlas y publicarlas en La Gaceta',
     'Organizar las elecciones y declarar sus resultados',
     'Fiscalizar el presupuesto nacional y sancionar el enriquecimiento ilícito',
     'Manual p.16 - Sección 1.5.4: El Poder Judicial tiene la función de conocer causas civiles, penales, comerciales, de trabajo y contencioso-administrativas, resolver sobre ellas y ejecutar las resoluciones.',
     'basico', 'p.16'),

    # ── 1.6 JURISDICCIÓN CONSTITUCIONAL ──────────────────────────────────────
    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué ley regula la Jurisdicción Constitucional y cuál es su objeto según el manual?',
     'La Ley N° 7135; garantizar la supremacía de las normas y principios constitucionales y del Derecho Internacional vigente, su uniforme interpretación y los derechos fundamentales',
     'La Ley N° 6227; regular las relaciones entre la Administración y los ciudadanos',
     'La Ley N° 8292; proteger y conservar el patrimonio público',
     'La Ley N° 7428; fiscalizar el uso de los recursos del Estado',
     'Manual p.17 - Sección 1.6: La Jurisdicción Constitucional está regulada por la Ley N° 7135, cuyo objeto es garantizar la supremacía constitucional, su uniforme interpretación y los derechos fundamentales.',
     'avanzado', 'p.17'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuáles son los seis recursos o acciones que tramita la Sala IV según el manual?',
     'Hábeas Corpus, Amparo, Acción de Inconstitucionalidad, Consulta Judicial, Consulta Legislativa de Constitucionalidad y Conflicto Constitucional',
     'Apelación, Casación, Revisión, Nulidad, Inconstitucionalidad y Reposición',
     'Amparo, Hábeas Corpus, Acción Civil, Acción Penal, Tutela y Cautela',
     'Inconstitucionalidad, Revisión, Apelación, Hábeas Data, Amparo y Mandato',
     'Manual p.17 - Sección 1.6: Los recursos que tramita la Sala IV son: Hábeas Corpus, Amparo, Acción de Inconstitucionalidad, Consulta Judicial, Consulta Legislativa de Constitucionalidad y Conflicto Constitucional.',
     'avanzado', 'p.17'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué protege el Recurso de Hábeas Corpus según el manual?',
     'La libertad e integridad de la persona humana frente a perturbaciones o restricciones ilegítimas, incluyendo la libertad de tránsito',
     'Los derechos humanos civiles, políticos, económicos, sociales y culturales consagrados en la Constitución',
     'La supremacía de las normas constitucionales sobre las leyes ordinarias',
     'Los derechos de los ciudadanos ante actos ilegales de particulares',
     'Manual p.17 - Sección 1.6: El Hábeas Corpus garantiza la libertad e integridad de la persona, la protege de restricciones ilegítimas y resguarda la libertad de tránsito.',
     'basico', 'p.17'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Contra quién se puede presentar el Recurso de Hábeas Corpus según el manual?',
     'Contra toda autoridad que amenace o prive ilegítimamente la libertad e integridad de una persona; también contra sujetos privados',
     'Únicamente contra autoridades públicas del Poder Ejecutivo',
     'Solo contra funcionarios judiciales que dicten sentencias ilegales',
     'Exclusivamente contra la policía y la fuerza pública',
     'Manual p.17 - Sección 1.6: El Hábeas Corpus se presenta contra toda autoridad que amenace o prive ilegítimamente la libertad; también contra sujetos privados.',
     'intermedio', 'p.17'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué derechos resguarda el Recurso de Amparo según el manual?',
     'Los derechos humanos, civiles, políticos, económicos, sociales y culturales de la Constitución e instrumentos internacionales, incluyendo vida, honor, igualdad, opinión, libre asociación, familia, infancia y ambiente',
     'Exclusivamente la libertad física y el derecho de tránsito de las personas',
     'Solo los derechos patrimoniales y económicos de los ciudadanos',
     'Únicamente los derechos políticos de los ciudadanos en época electoral',
     'Manual p.18 - Sección 1.6: El Amparo protege los derechos humanos, civiles, políticos, económicos, sociales y culturales; resguarda la vida, honor, igualdad, opinión, libre asociación, familia, infancia, ambiente, entre otros.',
     'intermedio', 'p.18'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Cuándo procede la Acción de Inconstitucionalidad según el manual?',
     'Contra leyes y disposiciones generales que lesionen el Derecho de la Constitución, o cuando en la formación de leyes se viole algún requisito o trámite constitucional esencial',
     'Cuando un ciudadano considera que una ley le afecta personalmente en sus derechos individuales',
     'Únicamente cuando el Presidente de la República veta una ley aprobada por la Asamblea',
     'Cuando hay conflictos entre instituciones autónomas sobre sus competencias',
     'Manual p.18 - Sección 1.6: La Acción de Inconstitucionalidad procede contra leyes y disposiciones generales que lesionen la Constitución, o cuando en su formación se viole algún requisito o trámite esencial.',
     'avanzado', 'p.18'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué es la Consulta Judicial de Constitucionalidad?',
     'Consultas presentadas por jueces ante la Sala IV para aclarar dudas de constitucionalidad sobre normas o actos que deben aplicar o juzgar',
     'Consultas de los ciudadanos a la Sala IV sobre la interpretación de sus derechos',
     'Consultas de los diputados sobre proyectos legislativos antes de su aprobación',
     'Consultas del Ejecutivo a la Sala sobre la constitucionalidad de decretos',
     'Manual p.18 - Sección 1.6: La Consulta Judicial son consultas presentadas por los jueces ante la Sala para aclarar dudas de constitucionalidad sobre normas o actos que deben aplicar o juzgar.',
     'avanzado', 'p.18'),

    ('1', 'Generalidades del Estado de Derecho',
     'La Consulta Legislativa de Constitucionalidad, ¿a cuántos diputados mínimo faculta y para qué?',
     'A un número no menor de 10 diputados, para solicitar a la Sala Constitucional su opinión previa sobre proyectos legislativos',
     'A un número no menor de 20 diputados, para solicitar la anulación de una ley vigente',
     'A un número no menor de 5 diputados, para declarar inconstitucional un decreto ejecutivo',
     'A un número no menor de 15 diputados, para suspender temporalmente la aplicación de una norma',
     'Manual p.18 - Sección 1.6: La Consulta Legislativa faculta a los diputados en número no menor a 10 para solicitar opinión previa de la Sala sobre proyectos legislativos.',
     'avanzado', 'p.18'),

    ('1', 'Generalidades del Estado de Derecho',
     '¿Qué son los Conflictos Constitucionales tramitados ante la Sala IV?',
     'Conflictos de competencia o atribuciones constitucionales entre los Poderes del Estado, el TSE, la CGR, entidades descentralizadas, municipalidades u otras personas de Derecho Público',
     'Disputas entre ciudadanos y el Estado por violaciones a derechos fundamentales individuales',
     'Controversias entre partidos políticos sobre el financiamiento electoral',
     'Conflictos laborales entre funcionarios y el Estado en materia de empleo público',
     'Manual p.18 - Sección 1.6: Los Conflictos Constitucionales son los relacionados con conflictos de competencia o atribuciones entre los Poderes del Estado y el TSE, o entre aquellos y la CGR, entidades descentralizadas, municipalidades y otras personas de Derecho Público.',
     'avanzado', 'p.18'),

    # BANCO DE PREGUNTAS - TEMA 2
    # La Administración Pública Costarricense
    # Fuente: Manual de Orientación para el Ingreso y Ejercicio de Puestos de Dirección Pública (2019)
    # Páginas 19-21 del manual

    # ── 2.1 CONCEPTO DE ADMINISTRACIÓN PÚBLICA ────────────────────────────────
    ('2', 'La Administración Pública Costarricense',
     'Según el Artículo 1 de la Ley 6227 citado en el manual, ¿por quiénes está constituida la Administración Pública?',
     'Por el Estado y los demás entes públicos, cada uno con personalidad jurídica y capacidad de derecho público y privado',
     'Por el Poder Ejecutivo y los Ministerios únicamente',
     'Por los tres Poderes del Estado y el Tribunal Supremo de Elecciones',
     'Por las instituciones autónomas y las municipalidades exclusivamente',
     'Manual p.19 - Sección 2.1: El Art. 1 de la Ley 6227 establece que "La Administración Pública estará constituida por el Estado y los demás entes públicos, cada uno con personalidad jurídica y capacidad de derecho público y privado".',
     'basico', 'p.19'),

    ('2', 'La Administración Pública Costarricense',
     'Según Romero (2002, p.9) citado en el manual, ¿qué afirma sobre la Administración Pública?',
     'Existe una Administración Pública en su unidad como el entero Estado-persona, pero también existe una pluralidad de centros de imputación jurídica, siendo las municipalidades y entidades descentralizadas también administraciones públicas',
     'La Administración Pública es únicamente el Poder Ejecutivo y sus ministerios dependientes',
     'La Administración Pública es un ente único y centralizado sin pluralidad de centros de imputación',
     'Solo el Estado central constituye la Administración Pública, excluyendo a los entes descentralizados',
     'Manual p.19 - Sección 2.1: Romero (2002, p.9) indica que existe una AP en su unidad (el Estado-persona), pero también una pluralidad de centros de imputación jurídica, siendo municipalidades y entidades descentralizadas también administraciones públicas.',
     'avanzado', 'p.19'),

    # ── 2.2 ORGANIZACIÓN DE LA ADMINISTRACIÓN PÚBLICA ─────────────────────────
    ('2', 'La Administración Pública Costarricense',
     '¿Cuáles son las dos grandes divisiones de la Administración Pública según el manual?',
     'Administración Pública Centralizada y Administración Pública Descentralizada',
     'Administración Nacional y Administración Municipal',
     'Administración Ejecutiva y Administración Judicial',
     'Administración Central y Administración Territorial',
     'Manual p.20 - Sección 2.2: La Administración Pública se divide en Centralizada (Ministerios y adscritas) y Descentralizada (Institucional y Territorial).',
     'basico', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     '¿Qué comprende la Administración Pública Centralizada según el manual?',
     'Los Ministerios y sus adscritas',
     'Las Instituciones Autónomas y Semiautónomas',
     'Las Municipalidades y los Consejos Municipales de Distrito',
     'Las Empresas Públicas Estatales y No Estatales',
     'Manual p.20 - Sección 2.2: La Administración Pública Centralizada comprende los Ministerios y sus adscritas.',
     'basico', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     '¿Cuáles son los tipos de entidades que conforman la Administración Pública Descentralizada Institucional según el manual?',
     'Instituciones Autónomas, Instituciones Semiautónomas, Empresas Públicas Estatales, Empresas Públicas No Estatales, Entes Administradores de Fondos Públicos y Entes Públicos No Estatales',
     'Ministerios, Viceministerios, Direcciones Generales y Departamentos',
     'Municipalidades, Concejos Municipales de Distrito y Gobernaciones',
     'Universidades, Hospitales, Bancos y Cooperativas del Estado',
     'Manual p.20 - Sección 2.2: La Descentralizada Institucional incluye: Instituciones Autónomas, Semiautónomas, Empresas Públicas Estatales, Empresas Públicas No Estatales, Entes Administradores de Fondos Públicos y Entes Públicos No Estatales.',
     'intermedio', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     '¿Qué conforma la Administración Pública Descentralizada Territorial?',
     '82 Municipalidades y 8 Consejos Municipales de Distrito',
     '7 Gobernaciones Provinciales y sus dependencias',
     'Los cantones y los distritos administrativos del país',
     'Las Juntas de Desarrollo Regional y los Concejos de Área',
     'Manual p.20 - Sección 2.2: La Administración Pública Descentralizada Territorial está conformada por 82 Municipalidades y 8 Consejos Municipales de Distrito.',
     'intermedio', 'p.20'),

    # ── 2.3 DIFERENCIAS ENTRE DESCONCENTRACIÓN Y DESCENTRALIZACIÓN ────────────
    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿qué caracteriza a la Desconcentración?',
     'Se produce al interior de un ente y consiste en otorgar una competencia del órgano superior al inferior',
     'Opera entre entes diferentes y otorga personería jurídica para cumplir con la competencia asignada',
     'Solo opera por medio de norma constitucional o ley y crea una nueva persona jurídica',
     'Implica transferencia de recursos del Poder Ejecutivo hacia un ente con autonomía plena',
     'Manual p.20 - Sección 2.3: La desconcentración se produce al interior de un ente y consiste en otorgar una competencia del órgano superior al inferior. Ejemplo: la Imprenta Nacional con el Ministerio de Gobernación y Policía.',
     'intermedio', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     '¿Qué ejemplo de desconcentración cita el manual?',
     'La Imprenta Nacional con el Ministerio de Gobernación y Policía',
     'La CCSS respecto al Ministerio de Salud',
     'La Universidad de Costa Rica respecto al Ministerio de Educación',
     'El ICE respecto al Ministerio de Ciencia y Tecnología',
     'Manual p.20 - Sección 2.3: El manual cita como ejemplo de desconcentración la Imprenta Nacional con el Ministerio de Gobernación y Policía.',
     'intermedio', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿qué caracteriza a la Descentralización?',
     'Solo opera por medio de norma constitucional o ley, es entre entes diferentes y otorga personería jurídica para cumplir con la competencia asignada',
     'Se produce al interior de un ente transfiriendo competencia del órgano superior al inferior sin personería',
     'Es un acuerdo voluntario entre instituciones para compartir funciones y recursos humanos',
     'Ocurre únicamente por decreto ejecutivo y mantiene la subordinación jerárquica al Ministerio rector',
     'Manual p.20 - Sección 2.3: La descentralización solo opera por norma constitucional o ley, es entre entes diferentes y otorga personería jurídica para cumplir la competencia asignada.',
     'intermedio', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     '¿Cuáles son los ejemplos de descentralización que cita el manual?',
     'CCSS, CONAPE, RACSA, ESPH y PROCOMER',
     'MIDEPLAN, Ministerio de Hacienda, BCCR y CGR',
     'ICE, AyA, RECOPE y FANAL',
     'INS, UCR, ITCR y UNED',
     'Manual p.20 - Sección 2.3: El manual cita como ejemplos de descentralización: CCSS, CONAPE, RACSA, ESPH y PROCOMER.',
     'avanzado', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿cuál es la diferencia fundamental entre desconcentración y descentralización?',
     'La desconcentración opera al interior de un mismo ente sin personería jurídica nueva, mientras que la descentralización es entre entes diferentes y otorga personería jurídica',
     'La desconcentración requiere ley y la descentralización solo requiere decreto ejecutivo',
     'La descentralización ocurre dentro del mismo ente y la desconcentración crea un nuevo ente con personería',
     'Ambos conceptos son sinónimos y se usan de forma intercambiable en la legislación costarricense',
     'Manual p.20 - Sección 2.3: La diferencia fundamental es que la desconcentración es al interior de un ente (sin nueva personería jurídica), mientras la descentralización es entre entes diferentes y otorga personería jurídica.',
     'avanzado', 'p.20'),

    # ── 2.4 DIFERENTES TIPOS DE AUTONOMÍA ─────────────────────────────────────
    ('2', 'La Administración Pública Costarricense',
     '¿Cuáles son los tres tipos de autonomía que presenta el manual?',
     'Autonomía Administrativa, Autonomía Política y Autonomía Organizativa',
     'Autonomía Financiera, Autonomía Técnica y Autonomía Jurídica',
     'Autonomía Presupuestaria, Autonomía Funcional y Autonomía Política',
     'Autonomía Legislativa, Autonomía Ejecutiva y Autonomía Judicial',
     'Manual p.20 - Sección 2.4: El manual presenta tres tipos de autonomía: Administrativa, Política y Organizativa.',
     'basico', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿en qué consiste la Autonomía Administrativa?',
     'Es la capacidad de autoadministrarse sin injerencias de terceros',
     'Es la capacidad de autodirigirse políticamente dentro del marco de su competencia legal',
     'Es la capacidad del ente de establecer su organización fundamental',
     'Es la potestad de crear y modificar su propia ley orgánica',
     'Manual p.20 - Sección 2.4: La Autonomía Administrativa es la capacidad de autoadministrarse sin injerencias de terceros.',
     'basico', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿en qué consiste la Autonomía Política?',
     'Es la capacidad de autodirigirse políticamente dentro del marco de su competencia legal',
     'Es la capacidad de autoadministrarse sin injerencias de terceros',
     'Es la capacidad del ente de establecer su organización fundamental',
     'Es la facultad de nombrar a sus propias autoridades sin intervención del Ejecutivo',
     'Manual p.20 - Sección 2.4: La Autonomía Política es la capacidad de autodirigirse políticamente dentro del marco de su competencia legal.',
     'basico', 'p.20'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿en qué consiste la Autonomía Organizativa?',
     'Es la capacidad del ente de establecer su organización fundamental',
     'Es la capacidad de autoadministrarse sin injerencias de terceros',
     'Es la capacidad de autodirigirse políticamente dentro del marco legal',
     'Es la potestad de dictar sus propias normas internas con fuerza de ley',
     'Manual p.20 - Sección 2.4: La Autonomía Organizativa es la capacidad del ente de establecer su organización fundamental.',
     'basico', 'p.20'),

    # ── 2.5 EL RÉGIMEN MUNICIPAL ───────────────────────────────────────────────
    ('2', 'La Administración Pública Costarricense',
     '¿En qué Título de la Constitución Política y en qué código está normado el régimen municipal?',
     'En el Título XII de la Constitución Política y en el Código Municipal',
     'En el Título IX de la Constitución Política y en la Ley de Municipalidades',
     'En el Título VIII de la Constitución Política y en la Ley Orgánica Municipal',
     'En el Título XI de la Constitución Política y en el Código Administrativo',
     'Manual p.21 - Sección 2.5: El régimen municipal está normado en el Título XII de la Constitución Política y en el Código Municipal.',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿qué es el Régimen Municipal desde el punto de vista de la descentralización?',
     'Es la aplicación de la descentralización territorial',
     'Es la aplicación de la desconcentración administrativa',
     'Es la aplicación de la autonomía política de los entes nacionales',
     'Es la aplicación de la centralización de los servicios locales',
     'Manual p.21 - Sección 2.5: El manual indica que el régimen municipal es la aplicación de la descentralización territorial (82 municipalidades).',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿qué tipo de autonomía poseen las Municipalidades?',
     'Las Municipalidades poseen autonomía',
     'Las Municipalidades poseen independencia total del Estado',
     'Las Municipalidades poseen autonomía únicamente administrativa',
     'Las Municipalidades poseen subordinación al Poder Ejecutivo',
     'Manual p.21 - Sección 2.5: El manual establece que "Las Municipalidades poseen autonomía".',
     'basico', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿qué ocurre con la transferencia de competencias a las Municipalidades?',
     'Existe transferencia de competencias del Poder Ejecutivo a las Municipalidades con los recursos respectivos',
     'El Poder Ejecutivo solo transfiere competencias sin recursos económicos asociados',
     'Las competencias se transfieren únicamente de la Asamblea Legislativa a las Municipalidades',
     'No existe transferencia de competencias; las Municipalidades crean sus propias por ley especial',
     'Manual p.21 - Sección 2.5: El manual indica que "Existe transferencia de competencias del Poder Ejecutivo a las Municipalidades con recursos respectivos".',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿cómo se elige el Gobierno Municipal?',
     'Mediante elecciones populares',
     'Mediante designación del Poder Ejecutivo',
     'Mediante nombramiento de la Asamblea Legislativa',
     'Mediante elección entre los funcionarios de la institución',
     'Manual p.21 - Sección 2.5: "La elección del Gobierno Municipal se efectúa mediante elecciones populares".',
     'basico', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     'Sobre los presupuestos municipales, ¿qué establece el manual?',
     'Las Municipalidades formulan sus presupuestos ordinarios y extraordinarios y los aprueba la Contraloría General de la República',
     'Las Municipalidades formulan sus presupuestos y los aprueba el Ministerio de Hacienda',
     'Los presupuestos municipales son aprobados directamente por la Asamblea Legislativa',
     'El Poder Ejecutivo formula y aprueba los presupuestos de las Municipalidades',
     'Manual p.21 - Sección 2.5: "Las Municipalidades formulan sus presupuestos ordinarios y extraordinarios y los aprueba la Contraloría General de la República".',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Cuáles son los tres tipos de cargos del Gobierno Municipal que menciona el manual?',
     'Alcalde Municipal, Síndicos y Regidores',
     'Alcalde Municipal, Viceintendente y Concejales',
     'Intendente, Síndicos y Regidores',
     'Alcalde Municipal, Secretario Municipal y Tesorero',
     'Manual p.21 - Sección 2.5: El manual menciona tres tipos de cargos en el Gobierno Municipal: Alcalde Municipal, Síndicos y Regidores.',
     'basico', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Qué detalla el Código Municipal según el manual?',
     'Las atribuciones, organización y funcionamiento de las municipalidades',
     'Los requisitos para ser electo como Alcalde o Regidor Municipal',
     'Los montos de transferencias del gobierno central a las municipalidades',
     'Los procedimientos de contratación administrativa de las municipalidades',
     'Manual p.21 - Sección 2.5: El Código Municipal detalla las atribuciones, organización y funcionamiento de las municipalidades.',
     'basico', 'p.21'),

    # ── 2.6 INSTITUCIONES AUTÓNOMAS Y SEMIAUTÓNOMAS ────────────────────────────
    ('2', 'La Administración Pública Costarricense',
     '¿En qué artículos de la Constitución Política están reguladas las instituciones autónomas según el manual?',
     'Artículos 188 a 190 de la Constitución Política',
     'Artículos 169 a 172 de la Constitución Política',
     'Artículos 183 y 184 de la Constitución Política',
     'Artículos 99 a 104 de la Constitución Política',
     'Manual p.21 - Sección 2.6: Las instituciones autónomas están reguladas en los artículos 188-190 de la Constitución Política.',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Qué tipo de autonomía tienen las instituciones autónomas según el manual?',
     'Cuentan con autonomía administrativa',
     'Cuentan con autonomía política plena',
     'Cuentan con autonomía organizativa y legislativa',
     'Cuentan con autonomía total e independencia del Estado',
     'Manual p.21 - Sección 2.6: Las instituciones autónomas cuentan con autonomía administrativa.',
     'basico', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Cuáles son los ejemplos de instituciones autónomas que cita el manual?',
     'Bancos del Estado, Universidades e INS',
     'CONAI, JUDESUR e ICODER',
     'CCSS, CONAPE y RACSA',
     'Imprenta Nacional, ESPH y PROCOMER',
     'Manual p.21 - Sección 2.6: El manual cita como ejemplos de instituciones autónomas los Bancos del Estado, las Universidades y el INS.',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿cuántos votos de diputados se requieren para modificar la ley orgánica o suprimir una institución autónoma?',
     '38 diputados',
     '29 diputados (mayoría simple)',
     '47 diputados (dos tercios)',
     '57 diputados (unanimidad)',
     'Manual p.21 - Sección 2.6: La modificación a la Ley Orgánica o eventual supresión de una institución autónoma requiere de los votos de 38 diputados.',
     'avanzado', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Cómo se crean las instituciones semiautónomas según el manual?',
     'Son creadas por la Asamblea Legislativa',
     'Son creadas por decreto del Poder Ejecutivo',
     'Son creadas por acuerdo del Consejo de Gobierno',
     'Son creadas por resolución de la Contraloría General de la República',
     'Manual p.21 - Sección 2.6: Las instituciones semiautónomas son creadas por la Asamblea Legislativa.',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Qué tipo de autonomía tienen las instituciones semiautónomas según el manual?',
     'Cuentan con autonomía administrativa',
     'Cuentan con autonomía política plena',
     'Cuentan con independencia total del Poder Ejecutivo',
     'No cuentan con ningún tipo de autonomía',
     'Manual p.21 - Sección 2.6: Las instituciones semiautónomas cuentan con autonomía administrativa.',
     'basico', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Cuáles son los ejemplos de instituciones semiautónomas que cita el manual?',
     'CONAI, JUDESUR e ICODER',
     'Bancos del Estado, Universidades e INS',
     'CCSS, CONAPE y RACSA',
     'ESPH, PROCOMER y FANAL',
     'Manual p.21 - Sección 2.6: El manual cita como ejemplos de instituciones semiautónomas: CONAI, JUDESUR e ICODER.',
     'intermedio', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     'Según el manual, ¿cuántos votos de diputados se requieren para modificar la ley orgánica o suprimir una institución semiautónoma?',
     'La mayoría de los diputados',
     '38 diputados',
     'Dos tercios de los diputados (38)',
     'La unanimidad de los 57 diputados',
     'Manual p.21 - Sección 2.6: La modificación a la Ley Orgánica o eventual supresión de una institución semiautónoma requiere del voto de la mayoría de los diputados.',
     'avanzado', 'p.21'),

    ('2', 'La Administración Pública Costarricense',
     '¿Cuál es la diferencia en el número de votos requeridos para modificar o suprimir una institución autónoma versus una semiautónoma?',
     'Para las autónomas se requieren 38 votos y para las semiautónomas la mayoría de los diputados',
     'Para las autónomas se requiere la mayoría y para las semiautónomas 38 votos',
     'Ambas requieren 38 votos, sin distinción entre tipos de institución',
     'Ambas requieren la mayoría de los diputados presentes en sesión',
     'Manual p.21 - Sección 2.6: Para autónomas se requieren 38 votos y para semiautónomas la mayoría de los diputados; en ambos casos para modificar su ley orgánica o suprimirlas.',
     'avanzado', 'p.21')

]